// Generated by Wrangler by running `wrangler types`

interface Env {
	NODE_ENV: "development";
	ORIGIN_URL: "http://127.0.0.1:5000";
	MONGO_URI: string;
	MONGO_DIRECT_URI: string;
	MONGO_SINGLE_NODE_URI: string;
}
