name: Build and Deploy Docker Container to Azure App Service

on:
  push:
    branches:
      - main # Workflow triggers on pushes to the 'main' branch.
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab.

env:
  AZURE_WEBAPP_NAME: bestvirtualclass                   # Your Azure App Service name
  DOCKER_IMAGE_NAME: yours7majesty/bestvirtualclass # Replace with your Docker Hub username and image name

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}'